### ISSUE TITLE
Color code bug?

### ISSUE THREAD

**Issue by AggerTV** [brainsynder-Dev/SimplePets#99] opened 2021-03-05 19:19 UTC
Please drop the Debug.json file generated from doing `/pet debug` here

**Describe the bug**
Color codes are not translated correctly
E.g https://gyazo.com/0603ce60347c56ccaa00bbe832dbf901

**Steps to reproduce**
Name a pet with color codes in their name

**Expected behavior**
the color codes to be translated into colors

**Screenshots/Videos (If you have any)**
https://gyazo.com/0603ce60347c56ccaa00bbe832dbf901

**Additional Information**
This server is running Tuinity version git-Tuinity-"7734ef0" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
SimplePets version 4.4 (build 60)

**Comment by Thatsmusic99** [comment] 2021-03-05 19:20
Duplicate of #94, restart your server and it does fix itself.

**Closed as completed by Thatsmusic99** 2021-03-05 19:20 UTC
Labels: Type: Bug
