### ISSUE TITLE
ClassNotFoundException when some players join

### ISSUE THREAD

**Issue by shroomdog27** [brainsynder-Dev/SimplePets#73] opened 2020-07-30 00:10 UTC
### What steps will reproduce the problem?
1. Install the latest version of Simple pets (v4.2.1 | Build #8)
2. Give a pet to yourself
3. Sometimes that exception will print when a player logs into the server.

### What were you expecting to happen? What happened instead?
I expected nothing to happen. Instead, the error printed

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://pastebin.com/4N8KvEiS

### Additional information? *(Did it work in previous versions? etc.)*
This server is running Paper version git-Paper-333 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Thatsmusic99** [comment] 2020-07-30 07:11
Duplicate of #67 which is already fixed.

Please check that issue for more information.

**Closed** 2020-07-30 07:34 UTC
