### ISSUE TITLE
Pet rename Bug

### ISSUE THREAD

**Issue by confuxeon** [brainsynder-Dev/SimplePets#65] opened 2020-05-31 10:28 UTC
### What steps will reproduce the problem?
1. /pet name
2. rename the pet
3. click the name tag while holding shift

### What were you expecting to happen? What happened instead?
Renaming the pet. But instead the pet gets renamed and you get the renamed nametag.
### Could you please do *"/pet debug"* and paste the link here:
We did not get the link.
### Additional information? *(Did it work in previous versions? etc.)*
We have successfully tested this bug a few months ago on older versions (1.12.2). It does work on 1.15.2 too.
We have forgotten to report this bug.

**Comment by Thatsmusic99** [comment] 2020-05-31 10:32
What does /version SimplePets say?

If you didn't download a build from Jenkins, it is recommended you try that first: http://ci.pluginwiki.us/job/SimplePets/29/

However, it has not been confirmed in the past that this was a bug and most likely was not fixed.

**Comment by Thatsmusic99** [comment] 2020-06-03 13:05
Successfully reproduced, will put it down as a bug to fix in the future. For now, set `RenamePet.ViaAnvil` to false in Config.yml to prevent the issue.

**Comment by Thatsmusic99** [comment] 2020-06-08 16:53
Confirmed fixed in the recent experimental builds.

**Comment by xMarcusG** [comment] 2020-06-09 15:38
Awesome! Glad a fix was produced as I have had the same issue too

**Comment by Thatsmusic99** [comment] 2020-07-24 17:39
Since the experimental builds are now considered stable enough to be used on production servers (please note we are only supporting 1.14, 1.15 and 1.16 in these builds), I will be closing this issue as it is fixed in that version.

**Closed by Thatsmusic99** 2020-07-24 17:39 UTC
Labels: bug
