### ISSUE TITLE
NPE on PlayerTeleportEvent with SimplePets v3.6.6

### ISSUE THREAD

**Issue by Prunt** [brainsynder-Dev/SimplePets#8] opened 2018-02-01 12:08 UTC
### What steps will reproduce the problem?  
1. Player is teleported somewhere
2. Presumably has a pet activated, but I'm not sure

### What were you expecting to happen? What happened instead?  
Expected no errors; got an error.

### What version of the plugin are you using? (Type /version &lt;Plugin Name&gt;)  
SimplePets version 3.6.6

### What Spigot version are you using? (Type /version)  
Paper version git-Paper-1320 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### What plugins are you using? (Type /plugins)
I'd rather not post them publicly.

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). (If you're not sure, upload your whole server log) 
https://hastebin.com/riburahula.hs

**Comment by brainsynder-Dev** [comment] 2018-02-01 14:31
Duplicate of: https://github.com/brainsynder-Dev/SimplePets/issues/7#issuecomment-362282148

**Closed by brainsynder-Dev** 2018-02-01 14:31 UTC
