### ISSUE TITLE
"Ride your pets" button

### ISSUE THREAD

**Issue by teon56** [brainsynder-Dev/SimplePets#112] opened 2021-06-28 16:44 UTC
### What steps will reproduce the problem?
1. paper 1.17 55
2. SimplePets_v5 Build 49

### What were you expecting to happen? What happened instead?

When you disable 'All-Pets-Hat' in config, the button "Ride your pets" in /pets gui disappear to

### Could you please do *"/pet debug"* and paste the link here:

https://www.pastelog.us/pucawipeva

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*

No error

**Comment by brainsynder-Dev** [comment] 2021-06-28 16:45
Will look into

**Comment by Thatsmusic99** [comment] 2021-07-06 07:55
Not sure if this was fixed by one of many recent commits made by Brian but I am unable to reproduce this on v5 build 58.

**Comment by Thatsmusic99** [comment] 2021-07-06 08:01
Yep, fixed in commit e5b88ac

**Closed as completed by Thatsmusic99** 2021-07-06 08:01 UTC
