### ISSUE TITLE
dosn't work at all for 1.16.3

### ISSUE THREAD

**Issue by LWQXa** [brainsynder-Dev/SimplePets#87] opened 2020-11-20 12:34 UTC
so my problem is that simplepets dosnt work at all for versoin 1.16.3
it shows me in the plugins as red
but /pets /pet does show 
if i try to typ the command or a command from the plugin it says that a error accurse and dosnt work

**Comment by Thatsmusic99** [comment] 2020-11-20 12:45
Alright, several things.

Firstly, you didn't fill out the issue template. This helps us locate issues better.

Secondly, this is a duplicate of #79 - which is closed - and #69, which is pinned right at the top of the issues page and is the very first pinned issue.

The issue template asks you to try an experimental build. These are found [here](http://ci.pluginwiki.us/job/SimplePets-Experimental/39/) and support 1.16.3; you need to download the SimplePets-1.16.3.jar file and upload it onto your server without reloading.

If you look to open future issues on SimplePets or any other repo/plugin at all, please always follow the issue template because otherwise we don't have enough information to reliably reproduce the problem. In addition, always check to see if your issue already exists or is closed. I apologise if I come off as rude or arrogant, but I'm hoping that this helps you - and other people - in the long run when contributing to other projects.

Please re-open the issue if the problem persists. If you have questions please either join the Discord in the Spigot description page or ask it here.

Thank you.

**Closed by Thatsmusic99** 2020-11-20 12:45 UTC
