### ISSUE TITLE
[BUG] Respawn-Last-Pet-On-Login doesn't respawn the pet when SQL enabled

### ISSUE THREAD

**Issue by Tyloon1e** [brainsynder-Dev/SimplePets#105] opened 2021-04-15 23:10 UTC
Please drop the Debug.json file generated from doing `/pet debug` here

**Describe the bug**
Respawn-Last-Pet-On-Login doesn't work as intended.

**Steps to reproduce**
1. Use default config
2. Enable SQL in config.yml and restart server
3. Summon pet and relog, pet isn't automatically spawned

**Expected behavior**
I expected the pet to spawn again. :P

**Screenshots/Videos (If you have any)**

**Additional Information**
Add any other context about the problem here?

**Comment by Tyloon1e** [comment] 2021-04-15 23:11
https://pastebin.com/raw/b0gi80k2

**Comment by Tyloon1e** [comment] 2021-05-29 23:16
Any updates on this?

**Comment by brainsynder-Dev** [comment] 2021-05-29 23:35
I have not personally been able to look into this mostly because I am trying to get v5 in a somewhat working order for when 1.17 comes out. (I know for a fact that is fixed in v5) [now that work has slowed down]

**Comment by Thatsmusic99** [comment] 2021-06-08 12:00
Oh man, I almost completely forgot to update this. [This bug should be patched in the v5 recode](https://ci.pluginwiki.us/job/SimplePets_v5/) but has not been tested for MySQL yet as I believe this bug occurred regardless of whether it was enabled or not.

And either way, the new alternative to MySQL is SQLite instead.

**Comment by Thatsmusic99** [comment] 2021-06-29 19:41
Confirmed to be fixed as of [v5 Build 53](https://ci.pluginwiki.us/job/SimplePets_v5/53/) which fixed the majority of issues within MySQL.

**Closed as completed by Thatsmusic99** 2021-06-29 19:41 UTC
Labels: Type: Bug
