### ISSUE TITLE
Error on start and when using debug command

### ISSUE THREAD

**Issue by camdenorrb** [brainsynder-Dev/SimplePets#67] opened 2020-06-02 22:53 UTC
### What steps will reproduce the problem?
1. Install plugin

### What were you expecting to happen? What happened instead?
Startup without errors, had errors

### Could you please do *"/pet debug"* and paste the link here:
![image](https://user-images.githubusercontent.com/5360339/83577295-741b9c80-a4f9-11ea-9a86-477d5cac30a3.png)

..Lmao

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://hastebin.com/ajapepowel.rb

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Yes

### Additional information? *(Did it work in previous versions? etc.)*

[18:51:31 INFO]: This server is running Paper version git-Paper-325 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Java 14.0.1 
AdoptOpenJDK OpenJ9 JVM

**Comment by Thatsmusic99** [comment] 2020-06-03 06:37
Just to confirm a few things with this bug:
- It’s been reported before on our Discord but first time on Github, but it should be easier for us to track.
- It does not occur upon startup; it occurs when a player joins.
- it only occurs when using Java 11.
- There have been no known effects of this bug; it’s really just an annoyance.
- It is an internal issue, meaning it is not a direct SimplePets problem and makes it a little harder to fix.
- We are looking to have it fixed once brainsynder has finished switching the internal library of SimplePets, where the old one would cause the error but the new one (hopefully) doesn’t. Should the new library cause this issue, we will investigate further and try to fix it.

Oh yes, and that debug command... yeah, that may be something we need to look into following the library switch, since currently I don’t want to change an exaggerated amount in the plugin.

**Comment by Thatsmusic99** [comment] 2020-06-09 07:40
Confirmed fixed after tweaking something in the new library. As of currently, the fix is not available, but I am looking to have the recode finished and given the green light by Friday.

Once the recode is available to everyone, I will be closing this issue and other issues that are fixed.

**Comment by Thatsmusic99** [comment] 2020-07-24 17:40
Since the experimental builds are now considered stable enough to be used on production servers (please note we are only supporting 1.14, 1.15 and 1.16 in these builds), I will be closing this issue as both problems are fixed in that version.

**Closed by Thatsmusic99** 2020-07-24 17:40 UTC
Labels: bug
