### ISSUE TITLE
SimplePets Pet Bug

### ISSUE THREAD

**Issue by RiactionCZ** [brainsynder-Dev/SimplePets#22] opened 2018-03-19 19:49 UTC
### What steps will reproduce the problem?
Video: https://youtu.be/4Af2Y-2vaas

### What were you expecting to happen? What happened instead?
I expected the pet after relog not to disappear.

### What version of the plugin are you using? *(Type /version <Plugin Name>)*
SimplePets version 3.9

### What Spigot version are you using? *(Type /version)*
Spigot 1.12.2 Build 201803190430, development

### What plugins are you using? *(Type /plugins)*
AsyncWorldEditInjector, PlayerHeads, WorldEdit, Cestinator, CommandLogger, Essentials, ClearChat, PlaceholderAPI, ClearLag, ArmorStandEditor, AutoMessage, PlugMan, PlayerLink, BouncySponge, AsyncWorldEdit, Admin-Chat, MaxBans, AntiAd, EssentialsChat, PermissionsEx, LagMeter, AntiJoinBot, ViaVersion, Tablist, SimpleAPI, Vault, ChairStairs, EssentialsSpawn, ViaBackwards, FakaHedaMinequery, HeadDatabase, ProtocolLib, HideAndCustomPlugins, ColoredTags, SuperVanish, PlotSquared, Multiverse-Core, SkinsRestorer, AuthMe, SimplePets

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
without error

### Are you using a beta version of SimplePets? *(If no, then please check if there is one [here](https://discord.gg/qGfnAfC) and give it a try)*: 
No Im using version 3.9

### Additional information? *(Did it work in previous versions? etc.)*
I dont have any addition information

**Comment by Thatsmusic99** [comment] 2018-03-19 19:51
Duplicate of https://github.com/brainsynder-Dev/SimplePets/issues/20 - to be fixed in v4.0.

**Closed** 2018-04-25 17:55 UTC
Labels: duplicate, fixed
