### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GlobooX** [brainsynder-Dev/SimplePets#5] opened 2018-01-26 22:42 UTC
My server crash with SimplePets plugin.
Spigot: 1.12
Plugin: latest version

Logs: https://pastebin.com/4SW4fkad, https://pastebin.com/DX1y7gNe

**Comment by brainsynder-Dev** [comment] 2018-01-26 23:54
Duplicate of: https://github.com/brainsynder-Dev/SimplePets/issues/4

**Closed by brainsynder-Dev** 2018-01-26 23:54 UTC
Labels: duplicate, fixed
