### ISSUE TITLE
Death with open inventory duplicates the name tags

### ISSUE THREAD

**Issue by Galajus** [brainsynder-Dev/SimplePets#93] opened 2021-01-20 05:06 UTC
### What steps will reproduce the problem?
1. open anvil to rename pet
2. die

**Comment by Thatsmusic99** [comment] 2021-01-20 17:46
Alright, you get the reward for managing to make me reproduce a bug with only 6 words, I think that's a new record.

**Comment by Thatsmusic99** [comment] 2021-06-29 20:37
Recently tested this one again on v5 since Brian changed the anvil library being used so it's not our system anymore. Happy to confirm this one is now fixed, but this is still going down as one of my favourite issues on Github for using so few words yet being so easy to reproduce. Good luck with your future endeavours, fella.

**Closed by Thatsmusic99** 2021-06-29 20:37 UTC
