### ISSUE TITLE
Unusual behaviour w/ Horse, Donkey, Mule and Ravager mounting

### ISSUE THREAD

**Issue by Darigsey** [brainsynder-Dev/SimplePets#60] opened 2020-04-22 07:57 UTC
the saddles don't go on the horses and There are mistakes when riding all types of horse and when you dismount it runs wild

I use:paper-206.jar
and: SimplePets Build #28  (21.04.2020 11:42:13) 

and sorry for my bad english

**Comment by Thatsmusic99** [comment] 2020-04-22 08:00
Both problems are currently known of with unknown solutions. The majority of this seems to be client-side which is why you dismount in strange places (another player would think you're riding the horse fine, see [this video](https://cdn.discordapp.com/attachments/243948414226661376/669600525494517771/2020-01-19_16-11-54.mp4) for reference).

**Comment by iLemon** [comment] 2020-05-29 21:35
I have players reporting this issue too.

**Comment by Thatsmusic99** [comment] 2020-06-03 12:42
Renamed to better fit its issue and also pinned.
- The issue currently affects horses, donkeys, mules and ravagers (any more please mention them)
- It seems present in the majority of versions
- The problem appears to be prevalent on the client's end; see the video I posted in an earlier comment.
- Players are teleported in unusual places because the server *thinks* that's where the player is; when a player sends a signal to the server to dismount, they are sent to where the server believes they should be.
- There is no known fix to this as of right now and will be an issue inspected deeply once SP's library is changed.

**Comment by Thatsmusic99** [comment] 2020-06-08 16:28
Confirmed partially fixed in the experimental builds (of which are not currently recommended), for some stupid reason all the mounts needed saddles to function properly.

However, because the ravager does not use saddles, it is not known what causes the problems with it.

**Comment by frengor** [comment] 2020-08-29 19:41
I think this is due to internal minecraft changes. The method a(float, float, float) in Entity class changed to e(Vec3D). If you check EntityPet class, you'll see the 3 floats are currently took from the Vec3D, like if they were group up into a single object, but it isn't. The Vec3D contains coordinates. Thus, the current method makes every pet moving diagonally.

**Comment by Thatsmusic99** [comment] 2020-08-29 20:35
It does not make all pets move diagonally, that was an issue fixed in the Jenkins build and is an entirely different issue. This bug only affects the ravager as of currently.

**Comment by brainsynder-Dev** [comment] 2020-09-01 03:50
Here is am update for this issue... 

I have it at a point where riding horse type pets does not break (unless you spam jump... then it breaks BIG time)

The Ravager is broken even more tho...... (does not move at all, and no idea why yet xD )

**Closed** 2021-07-06 07:42 UTC
Labels: bug
